# -*- coding: utf-8 -*-
"""Projeto_PUC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bz2oXK4y9wmn1n_eV6jAKjo8-rNWc-i8

###MENU PRINCIPAL
"""

def menu_principal():
    print("\nMenu Principal:")
    print("1. Estudantes")
    print("2. Disciplinas")
    print("3. Professores")
    print("4. Turmas")
    print("5. Matrículas")
    print("6. Sair")

    opcao = input("Escolha uma opção (número ou texto): ").strip().lower()

    if opcao in ["1", "estudantes"]:
        print("Você escolheu: Estudantes")
        menu_operacoes()
    elif opcao in ["2", "disciplinas"]:
        print("Você escolheu: Disciplinas")
        menu_operacoes()
    elif opcao in ["3", "professores"]:
        print("Você escolheu: Professores")
        menu_operacoes()
    elif opcao in ["4", "turmas"]:
        print("Você escolheu: Turmas")
        menu_operacoes()
    elif opcao in ["5", "matrículas", "matriculas"]:
        print("Você escolheu: Matrículas")
        menu_operacoes()
    elif opcao in ["6", "sair"]:
        print("Saindo do sistema.")
    else:
        print("Opção inválida.")

"""###MENU OPERAÇÕES"""

def menu_operacoes():
    print("\nMenu de Operações:")
    print("1. Incluir")
    print("2. Listar")
    print("3. Atualizar")
    print("4. Excluir")
    print("5. Voltar ao menu principal")

    operacao = input("Escolha uma operação (número ou texto): ").strip().lower()

    if operacao in ["1", "incluir"]:
        print("Você escolheu: Incluir")
    elif operacao in ["2", "listar"]:
        print("Você escolheu: Listar")
    elif operacao in ["3", "atualizar"]:
        print("Você escolheu: Atualizar")
    elif operacao in ["4", "excluir"]:
        print("Você escolheu: Excluir")
    elif operacao in ["5", "voltar", "voltar ao menu principal"]:
        print("Voltando ao menu principal... (não implementado)")
    else:
        print("Operação inválida.")

    print("Fim da aplicação.")

# Estruturas de dados para armazenar os registros
estudantes = []
professores = []
disciplinas = []
turmas = []
matriculas = []

# Função para incluir dados genéricos
def incluir_dados(nome, lista, dados_adicionais=None):
    try:
        codigo = int(input(f"Digite o código do {nome}: "))
        nome = input(f"Digite o nome do {nome}: ").strip()

        if nome:
            if dados_adicionais:
                lista.append({"codigo": codigo, "nome": nome, **dados_adicionais})
            else:
                lista.append({"codigo": codigo, "nome": nome})
            print(f"{nome} incluído com sucesso!")
        else:
            print(f"Nome inválido. Nenhum dado foi incluído.")
    except ValueError:
        print("Código inválido. Deve ser um número inteiro.")

# Função para listar dados genéricos
def listar_dados(lista):
    if lista:
        for item in lista:
            print(f"Código: {item['codigo']}, Nome: {item['nome']}")
    else:
        print("Não há dados cadastrados.")

# Função para excluir dados genéricos
def excluir_dados(codigo, lista):
    for item in lista:
        if item["codigo"] == codigo:
            lista.remove(item)
            print(f"Registro com código {codigo} removido com sucesso!")
            return
    print("Registro não encontrado.")

# Função para atualizar dados genéricos
def atualizar_dados(codigo, lista):
    for item in lista:
        if item["codigo"] == codigo:
            novo_codigo = int(input("Novo código: "))
            novo_nome = input("Novo nome: ").strip()
            item["codigo"] = novo_codigo
            item["nome"] = novo_nome
            print(f"Registro com código {codigo} atualizado com sucesso!")
            return
    print("Registro não encontrado.")

# Função para verificar se o código já existe
def verificar_codigo_existe(codigo, lista):
    for item in lista:
        if item["codigo"] == codigo:
            return True
    return False

# Módulo Estudantes
def incluir_estudante():
    incluir_dados("estudante", estudantes)

def listar_estudantes():
    listar_dados(estudantes)

def excluir_estudante():
    try:
        codigo = int(input("Digite o código do estudante que deseja excluir: "))
        excluir_dados(codigo, estudantes)
    except ValueError:
        print("Código inválido. Deve ser um número inteiro.")

# Módulo Professores
def incluir_professor():
    incluir_dados("professor", professores, {"cpf": input("Digite o CPF do professor: ").strip()})

def listar_professores():
    listar_dados(professores)

def excluir_professor():
    try:
        codigo = int(input("Digite o código do professor que deseja excluir: "))
        excluir_dados(codigo, professores)
    except ValueError:
        print("Código inválido. Deve ser um número inteiro.")

# Módulo Disciplinas
def incluir_disciplina():
    incluir_dados("disciplina", disciplinas)

def listar_disciplinas():
    listar_dados(disciplinas)

def excluir_disciplina():
    try:
        codigo = int(input("Digite o código da disciplina que deseja excluir: "))
        excluir_dados(codigo, disciplinas)
    except ValueError:
        print("Código inválido. Deve ser um número inteiro.")

# Módulo Turmas
def incluir_turma():
    codigo = int(input("Digite o código da turma: "))
    if verificar_codigo_existe(codigo, turmas):
        print("Código da turma já existe.")
    else:
        professor_codigo = int(input("Digite o código do professor: "))
        disciplina_codigo = int(input("Digite o código da disciplina: "))
        turmas.append({"codigo": codigo, "professor_codigo": professor_codigo, "disciplina_codigo": disciplina_codigo})
        print(f"Turma com código {codigo} incluída com sucesso!")

def listar_turmas():
    listar_dados(turmas)

def excluir_turma():
    try:
        codigo = int(input("Digite o código da turma que deseja excluir: "))
        excluir_dados(codigo, turmas)
    except ValueError:
        print("Código inválido. Deve ser um número inteiro.")

# Módulo Matrículas
def incluir_matricula():
    codigo_turma = int(input("Digite o código da turma: "))
    codigo_estudante = int(input("Digite o código do estudante: "))
    if verificar_codigo_existe(codigo_turma, turmas) and verificar_codigo_existe(codigo_estudante, estudantes):
        matriculas.append({"codigo_turma": codigo_turma, "codigo_estudante": codigo_estudante})
        print(f"Matrícula na turma {codigo_turma} para o estudante {codigo_estudante} realizada com sucesso!")
    else:
        print("Turma ou estudante não encontrados.")

def listar_matriculas():
    listar_dados(matriculas)

def excluir_matricula():
    try:
        codigo_turma = int(input("Digite o código da turma da matrícula que deseja excluir: "))
        codigo_estudante = int(input("Digite o código do estudante da matrícula que deseja excluir: "))
        for mat in matriculas:
            if mat["codigo_turma"] == codigo_turma and mat["codigo_estudante"] == codigo_estudante:
                matriculas.remove(mat)
                print(f"Matrícula na turma {codigo_turma} para o estudante {codigo_estudante} excluída com sucesso!")
                return
        print("Matrícula não encontrada.")
    except ValueError:
        print("Código inválido. Deve ser um número inteiro.")

# Menu principal
def menu_principal():
    while True:
        print("\nMenu Principal:")
        print("1. Estudantes")
        print("2. Disciplinas")
        print("3. Professores")
        print("4. Turmas")
        print("5. Matrículas")
        print("6. Sair")

        opcao = input("Escolha uma opção (número ou texto): ").strip().lower()

        if opcao in ["1", "estudantes"]:
            print("Você escolheu: Estudantes")
            menu_operacoes(estudantes, "estudante")
        elif opcao in ["2", "disciplinas"]:
            print("Você escolheu: Disciplinas")
            menu_operacoes(disciplinas, "disciplina")
        elif opcao in ["3", "professores"]:
            print("Você escolheu: Professores")
            menu_operacoes(professores, "professor")
        elif opcao in ["4", "turmas"]:
            print("Você escolheu: Turmas")
            menu_operacoes(turmas, "turma")
        elif opcao in ["5", "matrículas", "matriculas"]:
            print("Você escolheu: Matrículas")
            menu_operacoes(matriculas, "matricula")
        elif opcao in ["6", "sair"]:
            print("Saindo do sistema.")
            break
        else:
            print("Opção inválida. Tente novamente.")

# Menu de operações
def menu_operacoes(lista, tipo):
    while True:
        print("\nMenu de Operações:")
        print("1. Incluir")
        print("2. Listar")
        print("3. Atualizar")
        print("4. Excluir")
        print("5. Voltar ao menu principal")

        operacao = input("Escolha uma operação (número ou texto): ").strip().lower()

        if operacao in ["1", "incluir"]:
            if tipo == "estudante":
                incluir_estudante()
            elif tipo == "professor":
                incluir_professor()
            elif tipo == "disciplina":
                incluir_disciplina()
            elif tipo == "turma":
                incluir_turma()
            elif tipo == "matricula":
                incluir_matricula()
        elif operacao in ["2", "listar"]:
            if tipo == "estudante":
                listar_estudantes()
            elif tipo == "professor":
                listar_professores()
            elif tipo == "disciplina":
                listar_disciplinas()
            elif tipo == "turma":
                listar_turmas()
            elif tipo == "matricula":
                listar_matriculas()
        elif operacao in ["3", "atualizar"]:
            if tipo == "estudante":
                atualizar_dados(int(input("Digite o código do estudante que deseja atualizar: ")), estudantes)
            elif tipo == "professor":
                atualizar_dados(int(input("Digite o código do professor que deseja atualizar: ")), professores)
            elif tipo == "disciplina":
                atualizar_dados(int(input("Digite o código da disciplina que deseja atualizar: ")), disciplinas)
            elif tipo == "turma":
                atualizar_dados(int(input("Digite o código da turma que deseja atualizar: ")), turmas)
            elif tipo == "matricula":
                atualizar_dados(int(input("Digite o código da matrícula que deseja atualizar: ")), matriculas)
        elif operacao in ["4", "excluir"]:
            if tipo == "estudante":
                excluir_estudante()
            elif tipo == "professor":
                excluir_professor()
            elif tipo == "disciplina":
                excluir_disciplina()
            elif tipo == "turma":
                excluir_turma()
            elif tipo == "matricula":
                excluir_matricula()
        elif operacao in ["5", "voltar"]:
            break
        else:
            print("Opção inválida. Tente novamente.")

# Execução do menu principal
menu_principal()